# Generated by Django 3.1.7 on 2021-05-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=300)),
                ('locality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Chittagong', 'ctg'), ('Dhaka', 'dhaka'), ('Rajshahi', 'rajshahi'), ("cox'sbazar", "cox'sbazar")], max_length=50)),
                ('mobiles', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg')),
                ('myfile', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
